

BETA DIVERSITY

## EUPHOTIC
## PCA ordination - PROTIST - ALL
### Figure 4A
```{r pressure, echo=FALSE}
# perform RDA ordination
unconstrained_PCA_RDA_protist <-
  ps_protist_heter %>%
  #tax_fix()%>%
  subset_samples(photic_zone == "Euphotic") %>%
  #tax_filter(min_prevalence = 0.1, tax_level = "Genus") %>%
  #tax_agg("Genus") %>%
  tax_transform(trans = "clr") %>%
  ord_calc(method = "PCA") 
#> Proportional min_prevalence given: 0.1 --> min 23/222 samples.
# ord_calc will automatically infer you want a "PCA" here
# specify explicitly with method = "PCA", or you can pick another method

# create plot
rda_plot_protist <- unconstrained_PCA_RDA_protist %>%
  ord_plot(
    #plot_taxa = 1:10, 
    colour = "Water_mass", size = 2, shape = "Cruise.TAN",
    tax_vec_length = 3,
    auto_caption = TRUE
  )

# customise plot
customised_plot_rda_protist <- rda_plot_protist +
  stat_ellipse(aes(linetype = Water_mass, colour = Water_mass)) +
  #scale_colour_brewer(palette = "Set1") +
 # scale_color_manual(values = Water_mass_colors) +
  scale_shape_manual(values=c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14)) 
 # theme(legend.position = "bottom") 


# show plot
customised_plot_rda_protist

ggsave("PCA_unconstrained_EUPHOTIC_PROTIST.pdf", dpi = 300,  width = 12, height = 8, scale=1.2)

```
## CONSTRAINED Ordination + PERMANOVA - PROTIST -HETER. I will use the raw environmental NO3 variables

```{r pressure, echo=FALSE}
#In the metadata, I had some "na" that were confusing, as they were considered as a value and not NA. So, first I am removing na with NA and then I am transforming everything in numeric.


# Fix "na" and other problematic strings BEFORE coercion
sample_data(ps_protist_heter)$NO3[sample_data(ps_protist_heter)$NO3 == "na"] <- NA
sample_data(ps_protist_heter)$Chla_total[sample_data(ps_protist_heter)$Chla_total == "na"] <- NA

# Now safely convert to numeric
sample_data(ps_protist_heter)$NO3 <- as.numeric(sample_data(ps_protist_heter)$NO3)
sample_data(ps_protist_heter)$Chla_total <- as.numeric(sample_data(ps_protist_heter)$Chla_total)

ps_clean <- ps_protist_heter%>%
  subset_samples(photic_zone == "Euphotic")%>%
  subset_samples(!is.na(Sal) & !is.na(Temp) & !is.na(NO3) & !is.na(Chla_total)& !is.na(U_Cast))  #I am removing all the samples with no data on these variables. I am also removing the samples with U_Cast with no data, as I want to create median columns for some environmental variables (NO3 and Chla) and thse samples, we can´t group them somehow. They are mainly the TUFsamples and the McClane samples of cruise 1810 that we are missing the environmental data anyway
table(sample_data(ps_clean)$Cruise.TAN)


#Checking how many samples I have per water sample
table(sample_data(ps_clean)$Water_mass)
#Antarctic       SAW       STF       STW 
#      196       97        30        124 

table(sample_data(ps_clean)$Cruise.TAN) # KAH1303 is removed as we don't have any chl info about that cruise.c 
#TAN1203 TAN1212 TAN1516 TAN1702 TAN1802 TAN1810 TAN1901 TAN2101 
#      7      69      18      44      35      96      94      84 

# Also remove samples with total counts = 0
ps_clean <- prune_samples(sample_sums(ps_clean) > 0, ps_clean) #Before I used this line, as I was oing the dist_cal,I                                                                  was getting this message -> Warning: you have empty rows: their dissimilarities may be meaningless in method “bray”Warning: missing values in results. After that, everything seems to work well.


Bray_dists <-
ps_clean%>%
  #tax_filter(min_prevalence = 0.1, tax_level = "Genus") %>%
  #tax_agg("Genus") %>%
  tax_transform("identity") %>%
  dist_calc("bray")                 #(microViz)
#> Proportional min_prevalence given: 0.1 --> min 23/222 samples.

perm2 <- dist_permanova(data = Bray_dists, variables = c("Water_mass","Cruise.TAN","Sal", "Temp" ,"NO3", "Chla_total"), seed = 321)
# Dropping samples with missings: 392   |  Due to having Nas I was obtaining this comment. For that reason, I had to clean the samples with missing values. That´s what I did in the lines above creating ps_clean. After I checked with any(is.na(Bray_dists@dist)) , I ensured that we have no empty data and I proceeded with the analysis.
# 2025-05-06 15:41:42.123733 - Starting PERMANOVA with 999 perms with 1 processes. 


perm_get(perm2) # Permutation test for adonis under reduced model
#Permutation test for adonis under reduced model
#Marginal effects of terms
#Permutation: free
#Number of permutations: 999

#vegan::adonis2(formula = formula, data = metadata, permutations = n_perms, by = by, parallel = parall)
#            Df SumOfSqs      R2       F Pr(>F)    
#Water_mass   3    4.411 0.02725  6.6472  0.001 ***
#Cruise.TAN   7   22.212 0.13722 14.3438  0.001 ***
#Sal          1    0.396 0.00244  1.7880  0.007 ** 
#Temp         1    1.016 0.00628  4.5918  0.001 ***
#NO3          1    0.751 0.00464  3.3965  0.001 ***
#Chla_total   1    1.098 0.00679  4.9651  0.001 ***
#Residual   430   95.124 0.58767                   
#---
#Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

#PERMONOVA WITH NO CATEGORICAL VARIABLES
perm2 <- dist_permanova(data = Bray_dists, variables = c("Sal", "Temp" ,"NO3", "Chla_total"), seed = 321)
# Dropping samples with missings: 392   |  Due to having Nas I was obtaining this comment. For that reason, I had to clean the samples with missing values. That´s what I did in the lines above creating ps_clean. After I checked with any(is.na(Bray_dists@dist)) , I ensured that we have no empty data and I proceeded with the analysis.
# 2025-05-06 15:41:42.123733 - Starting PERMANOVA with 999 perms with 1 processes. 


perm_get(perm2) # Permutation test for adonis under reduced model
#Permutation test for adonis under reduced model
#Marginal effects of terms
#Permutation: free
#Number of permutations: 999

#vegan::adonis2(formula = formula, data = metadata, permutations = n_perms, by = by, parallel = parall)
#            Df SumOfSqs      R2       F Pr(>F)
#Sal          1    1.784 0.01102  6.2051  0.001 ***
#Temp         1    7.844 0.04846 27.2817  0.001 ***
#NO3          1    1.379 0.00852  4.7957  0.001 ***
#Chla_total   1    2.445 0.01510  8.5017  0.001 ***
#Residual   440  126.515 0.78160                   
#Total      444  161.866 1.00000    

ord_calc(perm2, constraints = c("Sal","Temp", "NO3","Chla_total")) %>%
  ord_plot(
    colour = "Water_mass", size = 2, shape = "Cruise.TAN",
    constraint_vec_style = list(colour = "black", size = 0.1),
    constraint_lab_style = list(colour = "black")
  ) +
  stat_ellipse(aes(colour = Water_mass)) +
  #xlim(-3, 3) +  # Adjust these values depending on your data
  #ylim(-3, 3) +   # Adjust these values depending on your data
  # scale_color_brewer(palette = "Dark2") +
 # scale_color_manual(values = Water_mass_colors) +
  scale_shape_manual(values=c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14)) 
  #scale_shape_manual(values=c(1, 2, 5, 7, 8, 10, 3, 6)) 

#> Centering (mean) and scaling (sd) the constraints and conditions:
#>  weight
#>  female
#,"MLD0.2C"
#, "MLD0.2C"


ggsave("RDA_Bray_contrained_EUPHOTIC_PROTIST_HET_TSal_Chla_NO3_raw.pdf", dpi = 300,  width = 12, height = 8)

```

